# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 0.1.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.totem_api import TotemApi


class TestTotemApi(unittest.TestCase):
    """TotemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TotemApi()

    def tearDown(self) -> None:
        pass

    def test_delete_totem_by_id(self) -> None:
        """Test case for delete_totem_by_id

        Delete a totem by ID
        """
        pass

    def test_get_all_totems(self) -> None:
        """Test case for get_all_totems

        Get all totems
        """
        pass

    def test_get_totem_config(self) -> None:
        """Test case for get_totem_config

        Get totem configuration
        """
        pass

    def test_register_totem(self) -> None:
        """Test case for register_totem

        Register a new totem
        """
        pass


if __name__ == '__main__':
    unittest.main()
