# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 0.1.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.fine_api import FineApi


class TestFineApi(unittest.TestCase):
    """FineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FineApi()

    def tearDown(self) -> None:
        pass

    def test_create_zone_fine(self) -> None:
        """Test case for create_zone_fine

        Create a new fine for a specific zone
        """
        pass

    def test_delete_fine_by_id(self) -> None:
        """Test case for delete_fine_by_id

        Delete a fine by ID
        """
        pass

    def test_delete_fines(self) -> None:
        """Test case for delete_fines

        Delete all fines
        """
        pass

    def test_get_fine_by_id(self) -> None:
        """Test case for get_fine_by_id

        Get fine by ID
        """
        pass

    def test_get_fines(self) -> None:
        """Test case for get_fines

        Get all fines
        """
        pass

    def test_get_user_fines(self) -> None:
        """Test case for get_user_fines

        Get all fines of the currently logged user
        """
        pass

    def test_get_zone_fines(self) -> None:
        """Test case for get_zone_fines

        Get all fines for a specific zone
        """
        pass


if __name__ == '__main__':
    unittest.main()
