# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://github.com/OpenParkProject/OPP-common/openapi.yaml)

    The version of the OpenAPI document: 1.0.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ticket_api import TicketApi


class TestTicketApi(unittest.TestCase):
    """TicketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TicketApi()

    def tearDown(self) -> None:
        pass

    def test_add_car_ticket(self) -> None:
        """Test case for add_car_ticket

        Buy a ticket for a car
        """
        pass

    def test_get_car_tickets(self) -> None:
        """Test case for get_car_tickets

        Get tickets by plate
        """
        pass

    def test_get_ticket_by_id(self) -> None:
        """Test case for get_ticket_by_id

        Get ticket by ID
        """
        pass

    def test_get_tickets(self) -> None:
        """Test case for get_tickets

        Get all tickets
        """
        pass

    def test_get_user_tickets(self) -> None:
        """Test case for get_user_tickets

        Get all tickets of a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
