# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 0.1.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.zone_request import ZoneRequest

class TestZoneRequest(unittest.TestCase):
    """ZoneRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZoneRequest:
        """Test ZoneRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZoneRequest`
        """
        model = ZoneRequest()
        if include_optional:
            return ZoneRequest(
                name = 'Downtown Zone',
                available = True,
                geometry = '{"type":"Polygon","coordinates":[[[0,0],[0,1],[1,1],[1,0],[0,0]]]}',
                metadata = {max_hours=3, special_rules=No overnight parking},
                price_offset = 2.0,
                price_lin = 1.5,
                price_exp = 0.75
            )
        else:
            return ZoneRequest(
                name = 'Downtown Zone',
                available = True,
                geometry = '{"type":"Polygon","coordinates":[[[0,0],[0,1],[1,1],[1,0],[0,0]]]}',
                price_offset = 2.0,
                price_lin = 1.5,
                price_exp = 0.75,
        )
        """

    def testZoneRequest(self):
        """Test ZoneRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
