# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 0.1.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.car_api import CarApi


class TestCarApi(unittest.TestCase):
    """CarApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CarApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_car(self) -> None:
        """Test case for add_user_car

        Add a new car to the currently logged user
        """
        pass

    def test_delete_cars(self) -> None:
        """Test case for delete_cars

        Delete all cars
        """
        pass

    def test_delete_user_car(self) -> None:
        """Test case for delete_user_car

        Delete an existing car from the currently logged user
        """
        pass

    def test_get_cars(self) -> None:
        """Test case for get_cars

        Get all cars
        """
        pass

    def test_get_user_cars(self) -> None:
        """Test case for get_user_cars

        Get all cars of the currently logged user
        """
        pass

    def test_update_user_car(self) -> None:
        """Test case for update_user_car

        Update an existing car of the currently logged user
        """
        pass


if __name__ == '__main__':
    unittest.main()
