# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 1.0.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.session_api import SessionApi


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionApi()

    def tearDown(self) -> None:
        pass

    def test_get_pub_key(self) -> None:
        """Test case for get_pub_key

        Get token public key
        """
        pass

    def test_get_session(self) -> None:
        """Test case for get_session

        Get current session (get new token)
        """
        pass

    def test_login(self) -> None:
        """Test case for login

        Login
        """
        pass

    def test_register(self) -> None:
        """Test case for register

        Register
        """
        pass


if __name__ == '__main__':
    unittest.main()
