# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 0.1.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.zone_user_role_api import ZoneUserRoleApi


class TestZoneUserRoleApi(unittest.TestCase):
    """ZoneUserRoleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ZoneUserRoleApi()

    def tearDown(self) -> None:
        pass

    def test_add_zone_user_role(self) -> None:
        """Test case for add_zone_user_role

        Add a user with a role to a zone
        """
        pass

    def test_get_zone_users(self) -> None:
        """Test case for get_zone_users

        Get all users with roles in a zone
        """
        pass

    def test_remove_zone_user_role(self) -> None:
        """Test case for remove_zone_user_role

        Remove a user from a zone
        """
        pass


if __name__ == '__main__':
    unittest.main()
