# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://github.com/OpenParkProject/OPP-common/openapi.yaml)

    The version of the OpenAPI document: 1.0.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.session_api import SessionApi


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionApi()

    def tearDown(self) -> None:
        pass

    def test_get_current_session(self) -> None:
        """Test case for get_current_session

        Get current logged user
        """
        pass

    def test_login(self) -> None:
        """Test case for login

        Login
        """
        pass

    def test_logout(self) -> None:
        """Test case for logout

        Logout
        """
        pass


if __name__ == '__main__':
    unittest.main()
