# coding: utf-8

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://github.com/OpenParkProject/OPP-common/openapi.yaml)

    The version of the OpenAPI document: 1.0.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ticket_response import TicketResponse

class TestTicketResponse(unittest.TestCase):
    """TicketResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TicketResponse:
        """Test TicketResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TicketResponse`
        """
        model = TicketResponse()
        if include_optional:
            return TicketResponse(
                id = 56,
                plate = 'ABC123',
                start_date = '2022-01-01T00:00:00Z',
                end_date = '2022-01-01T00:00:00Z',
                price = 10.0,
                status = 'active',
                creation_time = '2022-01-01T00:00:00Z'
            )
        else:
            return TicketResponse(
                id = 56,
                plate = 'ABC123',
                start_date = '2022-01-01T00:00:00Z',
                end_date = '2022-01-01T00:00:00Z',
                price = 10.0,
                status = 'active',
                creation_time = '2022-01-01T00:00:00Z',
        )
        """

    def testTicketResponse(self):
        """Test TicketResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
