# coding: utf-8

# flake8: noqa
"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 1.0.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.base_fine import BaseFine
from openapi_client.models.base_ticket import BaseTicket
from openapi_client.models.base_user import BaseUser
from openapi_client.models.car import Car
from openapi_client.models.fine_request import FineRequest
from openapi_client.models.fine_response import FineResponse
from openapi_client.models.get_pub_key200_response import GetPubKey200Response
from openapi_client.models.session_request import SessionRequest
from openapi_client.models.session_response import SessionResponse
from openapi_client.models.ticket_request import TicketRequest
from openapi_client.models.ticket_response import TicketResponse
from openapi_client.models.user_request import UserRequest
from openapi_client.models.user_response import UserResponse
