# coding: utf-8

# flake8: noqa

"""
    Open Park Project - OpenAPI 3.1

    The Open Park Project (OPP) is a free open-source project that aims to  provide a scalable and flexible platform for the management of parking areas.  Some useful links: - [Open Park Project](https://github.com/OpenParkProject) - [API definition](https://raw.githubusercontent.com/OpenParkProject/OPP-common/refs/heads/main/openapi.yaml)

    The version of the OpenAPI document: 0.1.0
    Contact: tollsimy.dev@protonmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CarApi",
    "FineApi",
    "PaymentApi",
    "SessionApi",
    "TicketApi",
    "TotemApi",
    "UserApi",
    "ZoneApi",
    "ZoneUserRoleApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BaseFine",
    "BaseTicket",
    "BaseTotem",
    "BaseUser",
    "Car",
    "FineRequest",
    "FineResponse",
    "GetPubKey200Response",
    "GetUserByOTP200Response",
    "OTPResponse",
    "OTPValidationRequest",
    "SessionRequest",
    "SessionResponse",
    "TicketRequest",
    "TicketResponse",
    "TotemRequest",
    "TotemResponse",
    "UpdateUserRequest",
    "UserRequest",
    "UserResponse",
    "ZoneRequest",
    "ZoneResponse",
    "ZoneUserRoleBase",
    "ZoneUserRoleRequest",
    "ZoneUserRoleResponse",
]

# import apis into sdk package
from openapi_client.api.car_api import CarApi as CarApi
from openapi_client.api.fine_api import FineApi as FineApi
from openapi_client.api.payment_api import PaymentApi as PaymentApi
from openapi_client.api.session_api import SessionApi as SessionApi
from openapi_client.api.ticket_api import TicketApi as TicketApi
from openapi_client.api.totem_api import TotemApi as TotemApi
from openapi_client.api.user_api import UserApi as UserApi
from openapi_client.api.zone_api import ZoneApi as ZoneApi
from openapi_client.api.zone_user_role_api import ZoneUserRoleApi as ZoneUserRoleApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.base_fine import BaseFine as BaseFine
from openapi_client.models.base_ticket import BaseTicket as BaseTicket
from openapi_client.models.base_totem import BaseTotem as BaseTotem
from openapi_client.models.base_user import BaseUser as BaseUser
from openapi_client.models.car import Car as Car
from openapi_client.models.fine_request import FineRequest as FineRequest
from openapi_client.models.fine_response import FineResponse as FineResponse
from openapi_client.models.get_pub_key200_response import GetPubKey200Response as GetPubKey200Response
from openapi_client.models.get_user_by_otp200_response import GetUserByOTP200Response as GetUserByOTP200Response
from openapi_client.models.otp_response import OTPResponse as OTPResponse
from openapi_client.models.otp_validation_request import OTPValidationRequest as OTPValidationRequest
from openapi_client.models.session_request import SessionRequest as SessionRequest
from openapi_client.models.session_response import SessionResponse as SessionResponse
from openapi_client.models.ticket_request import TicketRequest as TicketRequest
from openapi_client.models.ticket_response import TicketResponse as TicketResponse
from openapi_client.models.totem_request import TotemRequest as TotemRequest
from openapi_client.models.totem_response import TotemResponse as TotemResponse
from openapi_client.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from openapi_client.models.user_request import UserRequest as UserRequest
from openapi_client.models.user_response import UserResponse as UserResponse
from openapi_client.models.zone_request import ZoneRequest as ZoneRequest
from openapi_client.models.zone_response import ZoneResponse as ZoneResponse
from openapi_client.models.zone_user_role_base import ZoneUserRoleBase as ZoneUserRoleBase
from openapi_client.models.zone_user_role_request import ZoneUserRoleRequest as ZoneUserRoleRequest
from openapi_client.models.zone_user_role_response import ZoneUserRoleResponse as ZoneUserRoleResponse
