name: Validate and generate API, trigger updates

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: openapitools/openapi-generator-cli
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate API
        run: openapi-generator-cli validate -i openapi.yaml

  generate:
    runs-on: ubuntu-latest
    container:
      image: openapitools/openapi-generator-cli
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate API clients
        run: openapi-generator-cli generate -i openapi.yaml -g dart-dio -o dart-client
      - name: Generate API server
        run: openapi-generator-cli generate -i openapi.yaml -g go-gin-server -o go-gin-server

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-generated
          path: |
            dart-client
            go-gin-server

  release:
      runs-on: ubuntu-latest
      needs: generate
      steps:
        - uses: actions/checkout@v4
        
        - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            name: api-generated
        
        - name: Compress artifacts
          run: |
            tar -czf dart-client.tar.gz dart-client
            tar -czf go-gin-server.tar.gz go-gin-server
        
        - name: Create GitHub Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            VERSION="v$(date +'%Y.%m.%d.%H%M')"
            gh release create $VERSION \
              --title "API $VERSION" \
              --notes "Automated API release generated from OpenAPI spec" \
              dart-client.zip \
              go-gin-server.zip

  trigger-frontend:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Trigger repository_dispatch in OPP-frontend
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: OpenParkProject/OPP-frontend
          event-type: OPP-common-updated
  
  trigger-backend:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Trigger repository_dispatch in OPP-backend
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: OpenParkProject/OPP-backend
          event-type: OPP-common-updated